name: Publish

on:
  push:
    branches:
      - main

  workflow_run:
    workflows: ["Deploy - Production"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@main
      - run: cd packages/pay
      - run: npx jsr publish
